### ISSUE TITLE
Multiple packages found with the same name

### ISSUE THREAD

**Issue by mzarswri** [lis-epfl/vswarm#5]
Hi,

I installed everything successfully, but when I try to update dependencies with `rosdep install --from-paths ~/catkin_ws/ --ignore-src -r -y`, I get the following errors:

ERROR: Rosdep experienced an error: Multiple packages found with the same name "mavlink":
- devel/share/mavlink
- src/mavlink
Multiple packages found with the same name "orocos_kdl":
- devel/share/orocos_kdl
- src/orocos_kinematics_dynamics/orocos_kdl
Multiple packages found with the same name "python_orocos_kdl":
- devel/share/python_orocos_kdl
- src/orocos_kinematics_dynamics/python_orocos_kdl

**Comment by lithiumhydride2** [comment]
I also encountered the same problem, could you tell me how to fix it.
